<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #ffcc00; background-color: #2a2a2a; padding: 30px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3); margin-bottom: 20px;">
    Data Mining
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #ff9900; background-color: #333333; padding: 20px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3); margin-bottom: 20px;">
    Lab 05
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #ff6600; background-color: #1c1c1c; padding: 20px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3); margin-bottom: 20px;">
    Syed Mansoor ul Hassan Bukhari
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #ffcc00; background-color: #222222; padding: 20px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3); margin-bottom: 20px;">
    BSAI - VII
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #ff3300; background-color: #1c1c1c; padding: 20px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);">
    2021-25
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 48px; font-weight: bold; text-align: center; color: #3399ff; background-color: #1c1c1c; padding: 20px; border: 3px solid #444; border-radius: 15px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);">
    <span style="position: relative; top: -10px;">19<sup>th</sup></span> Nov, 2024
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 20px; text-align: left; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <strong style="color: #ffcc00;">Question 01: </strong>
    <span style="color: #cccccc;">Select the Dataset of your own choice from the following Repositories.</span>
    <ul style="color: #cccccc;">
        <li>UCI Repository: <a href="http://www.ics.uci.edu/~mlearn/MLRepository.html" style="color: #ffcc00;">http://www.ics.uci.edu/~mlearn/MLRepository.html</a></li>
        <li>Statlib: <a href="http://lib.stat.cmu.edu/" style="color: #ffcc00;">http://lib.stat.cmu.edu/</a></li>
    </ul>
    <span style="color: #cccccc;">Apply Data Cleaning.</span>
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 20px; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <strong style="color: #ffcc00;">Applying Data Cleaning on the Dataset</strong></br></br>
    <span style="color: #cccccc;">In this section, we perform data cleaning on the selected dataset <span style="color: #ffcc00;">Dirtbike Dataset</span> from Statlib. Data cleaning is essential for preparing the dataset for analysis, and this step involves handling missing values, correcting inconsistencies, and ensuring the data is in a suitable format.</span></br></br>
</div>

<div style="font-family: 'Arial', sans-serif; font-size: 20px; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
<center>
  <span style="color:#ffcc00; font-size:22px; font-weight: bold; padding: 5px;">Import Libraries</span>
</center>
</div>

In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

<div style="font-family: 'Arial', sans-serif; font-size: 20px; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">    <strong style="color: #ffcc00;">1. Load the Dataset</strong></br>
    <pre style="color: #cccccc; background-color: #333333; padding: 10px;">
        url = "https://lib.stat.cmu.edu/datasets/dirtbike_aug.csv"
        dataset = pd.read_csv(url)
    </pre>
</div>

In [2]:
url = 'https://lib.stat.cmu.edu/datasets/dirtbike_aug.csv'
df = pd.read_csv(url)

<div style="font-family: 'Arial', sans-serif; font-size: 20px; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">    <strong style="color: #ffcc00;">2. Inspect the Dataset</strong></br>
    <span style="color: #cccccc;">Before cleaning, it is important to inspect the dataset for missing values, duplicate records, and inconsistent formatting. We check the first few rows to understand its structure:</span></br>
    <pre style="color: #cccccc; background-color: #333333; padding: 10px;">
        dataset.head()
    </pre>
</div>

In [3]:
df.head()

,model,manufacture,color,msrp,engine.cylinder,engine.stroke,displacement,bore,stroke,comp.ratio,...,front.brake,rear.brake,wheelbase,seat.height,overall.length,overall.width,overall.height,clearance,fuel.cap,total.weight
0,HondaCR85R,Honda,red,2999,1,2,84.0,48,48.0,8.0,...,disc,disc,49.1,32.4,NaN,NaN,NaN,12.2,1.35,144.0
1,HondaCR85RB,Honda,red,3099,1,2,84.0,48,48.0,8.0,...,disc,disc,49.1,34.0,NaN,NaN,NaN,13.9,1.35,145.0
2,HondaCRF100F,Honda,red,2249,1,4,99.0,53,45.0,9.0,...,drum,drum,49.2,30.9,NaN,NaN,NaN,10.0,1.50,165.0
3,HondaCRF150F,Honda,red,2999,1,4,157.0,64,49.0,9.0,...,disc,drum,52.2,32.5,NaN,NaN,NaN,10.0,2.20,216.0
4,HondaCRF230F,Honda,red,3499,1,4,223.0,66,66.0,9.0,...,disc,drum,54.1,34.1,NaN,NaN,NaN,11.7,2.20,238.0

<div style="font-family: 'Arial', sans-serif; font-size: 20px; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <strong style="color: #ffcc00;">3. Handle Missing Data</strong></br>
    <span style="color: #cccccc;">We check for missing values and decide how to handle them—either by filling them with appropriate values or dropping rows/columns with missing data:</span></br>
    <pre style="color: #cccccc; background-color: #333333; padding: 10px;">
        dataset.isnull().sum()  # Check for missing values
        dataset.fillna(0)  # Example: Fill missing values with 0
    </pre>
</div>

In [4]:
df.isna().sum()

model                0
manufacture          0
color                0
msrp                 0
engine.cylinder      0
engine.stroke        0
displacement         0
bore                 0
stroke               0
comp.ratio          27
starter             75
transmission         1
lubricator          65
final.drive         35
cooling             20
clutch              82
ignition             1
frame               67
front.suspension     0
rear.suspension      0
front.brake          0
rear.brake           0
wheelbase            1
seat.height          3
overall.length      54
overall.width       54
overall.height      55
clearance            3
fuel.cap             1
total.weight         1
dtype: int64

In [5]:
df.shape

(104, 30)

<div style="font-family: 'Arial', sans-serif; font-size: 20px; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
<center>
  <span style="color:#4682B4; font-size:22px; font-weight: bold; padding: 5px;">Filter columns where the missing percentage is less than the threshold
</span>
</center>
</div>

In [6]:
threshold = 0.5  # 50% threshold
# Calculate the percentage of missing values for each column
missing_percentage = df.isnull().mean()
df_cleaned = df.loc[:, missing_percentage < threshold]

In [7]:
# Check the shape after removing columns
print(f"Original shape: {df.shape}")
print(f"Shape after removing high-missing columns: {df_cleaned.shape}")

Original shape: (104, 30)
Shape after removing high-missing columns: (104, 23)

In [8]:
df = df_cleaned
df.isna().sum()

model                0
manufacture          0
color                0
msrp                 0
engine.cylinder      0
engine.stroke        0
displacement         0
bore                 0
stroke               0
comp.ratio          27
transmission         1
final.drive         35
cooling             20
ignition             1
front.suspension     0
rear.suspension      0
front.brake          0
rear.brake           0
wheelbase            1
seat.height          3
clearance            3
fuel.cap             1
total.weight         1
dtype: int64

<div style="font-family: 'Arial', sans-serif; font-size: 20px; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
<center>
  <span style="color:#4682B4; font-size:22px; font-weight: bold; padding: 5px;">Fill missing values for numerical columns with the mean</span>
</center>
</div>

In [9]:
df.loc[:, 'comp.ratio'] = df['comp.ratio'].fillna(df['comp.ratio'].mean())

In [10]:
df.dtypes

model                object
manufacture          object
color                object
msrp                  int64
engine.cylinder       int64
engine.stroke         int64
displacement        float64
bore                  int64
stroke              float64
comp.ratio          float64
transmission        float64
final.drive          object
cooling              object
ignition             object
front.suspension     object
rear.suspension      object
front.brake          object
rear.brake           object
wheelbase           float64
seat.height         float64
clearance           float64
fuel.cap            float64
total.weight        float64
dtype: object

<div style="font-family: 'Arial', sans-serif; font-size: 20px; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
<center>
  <span style="color:#4682B4; font-size:22px; font-weight: bold; padding: 5px;">Fill Low Missing Value with Mode</span>
</center>
</div>

In [11]:
df.loc[:, 'transmission'] = df['transmission'].fillna(df['transmission'].mode()[0])
df.loc[:, 'ignition'] = df['ignition'].fillna(df['ignition'].mode()[0])
df.loc[:, 'wheelbase'] = df['wheelbase'].fillna(df['wheelbase'].mode()[0])
df.loc[:, 'seat.height'] = df['seat.height'].fillna(df['seat.height'].mean())
df.loc[:, 'clearance'] = df['clearance'].fillna(df['clearance'].mean())
df.loc[:, 'fuel.cap'] = df['fuel.cap'].fillna(df['fuel.cap'].mode()[0])
df.loc[:, 'total.weight'] = df['total.weight'].fillna(df['total.weight'].mode()[0])

In [12]:
df.isna().sum()

model                0
manufacture          0
color                0
msrp                 0
engine.cylinder      0
engine.stroke        0
displacement         0
bore                 0
stroke               0
comp.ratio           0
transmission         0
final.drive         35
cooling             20
ignition             0
front.suspension     0
rear.suspension      0
front.brake          0
rear.brake           0
wheelbase            0
seat.height          0
clearance            0
fuel.cap             0
total.weight         0
dtype: int64

In [13]:
df['final.drive'].head(2)

0    chain
1    chain
Name: final.drive, dtype: object

In [14]:
# Drop the 'final.drive' column
df.drop(columns=['final.drive'], inplace=True)

In [15]:
df['cooling'].tail(2)

102    liquid
103    liquid
Name: cooling, dtype: object

In [16]:
df.dropna(inplace=True)

<div style="font-family: 'Arial', sans-serif; font-size: 20px; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">    <strong style="color: #ffcc00;">4. Remove Duplicates</strong><br>
    <span style="color: #cccccc;">Next, we remove any duplicate rows that may be present in the dataset:</span><br>
    <pre style="color: #cccccc; background-color: #333333; padding: 10px;">
        dataset = dataset.drop_duplicates()
    </pre>
</div>

In [18]:
df.duplicated().sum()

0

<div style="font-family: 'Arial', sans-serif; font-size: 20px; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">
    <strong style="color: #ffcc00;">5. Correct Data Types</strong></br>
    <span style="color: #cccccc;">It is crucial that each column has the correct data type. We check and correct the data types as necessary:</span></br>
    <pre style="color: #cccccc; background-color: #333333; padding: 10px;">
        dataset.dtypes  # Check the data types of each column
        dataset['column_name'] = dataset['column_name'].astype('desired_type')  # Example to convert data type
    </pre>
</div>

In [20]:
df.dtypes

model                object
manufacture          object
color                object
msrp                  int64
engine.cylinder       int64
engine.stroke         int64
displacement        float64
bore                  int64
stroke              float64
comp.ratio          float64
transmission        float64
cooling              object
ignition             object
front.suspension     object
rear.suspension      object
front.brake          object
rear.brake           object
wheelbase           float64
seat.height         float64
clearance           float64
fuel.cap            float64
total.weight        float64
dtype: object

In [21]:
df.head(3)

,model,manufacture,color,msrp,engine.cylinder,engine.stroke,displacement,bore,stroke,comp.ratio,...,ignition,front.suspension,rear.suspension,front.brake,rear.brake,wheelbase,seat.height,clearance,fuel.cap,total.weight
16,KawasakiKDX200,Kawasaki,green,4099,1,2,198.0,66,58.0,8.0,...,electronic,cartridge fork,single shock,disc,disc,56.5,36.2,13.4,2.90,222.6
17,KawasakiKDX220R,Kawasaki,green,4499,1,2,216.0,69,58.0,7.0,...,electronic,cartridge fork,single shock,disc,disc,56.5,36.2,13.4,2.90,222.6
18,KawasakiKDX50,Kawasaki,green,1099,1,2,49.0,41,38.0,6.0,...,digital,telescopic fork,twin shock,drum,drum,33.9,18.9,4.5,0.53,84.0

<div style="font-family: 'Arial', sans-serif; font-size: 20px; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">  <strong style="color: #ffcc00;">6. Normalize or Scale Data</strong></br>
    <span style="color: #cccccc;">If necessary, we can normalize or scale numerical data to ensure consistency and improve the performance of machine learning algorithms:</span></br>
    <pre style="color: #cccccc; background-color: #333333; padding: 10px;">
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    dataset[['numerical_column']] = scaler.fit_transform(dataset[['numerical_column']])
    </pre>
</div>

In [25]:
scaler = StandardScaler()

In [26]:
# Select the numerical columns for scaling
numerical_columns = ['msrp', 'engine.cylinder', 'engine.stroke', 'displacement', 'bore', 
                     'stroke', 'comp.ratio', 'transmission', 'wheelbase', 'seat.height', 
                     'clearance', 'fuel.cap', 'total.weight']

In [27]:
# Fit and transform the selected numerical columns
df[numerical_columns] = scaler.fit_transform(df[numerical_columns])

In [28]:
# Check the first few rows to confirm scaling
df[numerical_columns].head()

,msrp,engine.cylinder,engine.stroke,displacement,bore,stroke,comp.ratio,transmission,wheelbase,seat.height,clearance,fuel.cap,total.weight
16,-0.362894,0.0,-1.183216,-0.380542,-0.224928,0.018533,-1.500862,0.721076,0.467080,0.523499,0.367491,1.059094,0.410008
17,-0.200925,0.0,-1.183216,-0.272155,-0.072557,0.018533,-2.214308,0.721076,0.467080,0.523499,0.367491,1.059094,0.410008
18,-1.577668,0.0,-1.183216,-1.277738,-1.494684,-1.865051,-2.927754,-2.972240,-2.736332,-2.772050,-2.954930,-1.527954,-1.946461
19,-0.362894,0.0,0.845154,-0.073447,0.181394,0.018533,0.639476,0.721076,0.353685,0.047263,-0.677765,1.059094,1.011877
20,0.042030,0.0,0.845154,2.347178,1.501940,2.373014,-0.073970,-0.017587,0.807265,0.294906,-1.125732,4.552155,2.355030

<div style="font-family: 'Arial', sans-serif; font-size: 20px; color: #ffffff; background-color: #2d2d2d; padding: 25px; border: 3px solid #555555; border-radius: 15px; box-shadow: 0 6px 15px rgba(0, 0, 0, 0.4); margin-bottom: 25px;">    <strong style="color: #ffcc00;">7. Verify Cleaned Data</strong></br>
    <span style="color: #cccccc;">Finally, we verify that the dataset has been cleaned and is ready for further analysis:</span></br>
    <pre style="color: #cccccc; background-color: #333333; padding: 10px;">
        dataset.head()  # Verify cleaned data
    </pre>
</div>

In [29]:
df.head()

,model,manufacture,color,msrp,engine.cylinder,engine.stroke,displacement,bore,stroke,comp.ratio,...,ignition,front.suspension,rear.suspension,front.brake,rear.brake,wheelbase,seat.height,clearance,fuel.cap,total.weight
16,KawasakiKDX200,Kawasaki,green,-0.362894,0.0,-1.183216,-0.380542,-0.224928,0.018533,-1.500862,...,electronic,cartridge fork,single shock,disc,disc,0.467080,0.523499,0.367491,1.059094,0.410008
17,KawasakiKDX220R,Kawasaki,green,-0.200925,0.0,-1.183216,-0.272155,-0.072557,0.018533,-2.214308,...,electronic,cartridge fork,single shock,disc,disc,0.467080,0.523499,0.367491,1.059094,0.410008
18,KawasakiKDX50,Kawasaki,green,-1.577668,0.0,-1.183216,-1.277738,-1.494684,-1.865051,-2.927754,...,digital,telescopic fork,twin shock,drum,drum,-2.736332,-2.772050,-2.954930,-1.527954,-1.946461
19,KawasakiKLR250,Kawasaki,red,-0.362894,0.0,0.845154,-0.073447,0.181394,0.018533,0.639476,...,CDI,telescopic fork,single shock,disc,drum,0.353685,0.047263,-0.677765,1.059094,1.011877
20,KawasakiKLR650,Kawasaki,red,0.042030,0.0,0.845154,2.347178,1.501940,2.373014,-0.073970,...,electronic,air adjustable fork,single shock,disc,disc,0.807265,0.294906,-1.125732,4.552155,2.355030